
---
version: '1'

# App (Project) name
name: Fx-Sample

# App description
description: Fx Testing.

# license
licenses:
  - APACHE LICENSE, VERSION 2.

imports:
  '@USName': FxLabs/Common/US-Names
  
  # SQL Injection Strings 
  '@GenericSQLInjections': FxLabs/Common/Generic-SQLInjections
  '@OracleSQLInjections': FxLabs/Common/Oracle-SQLInjections
  '@PostgresSQLInjections': FxLabs/Common/Postgres-SQLInjections
  '@SQLServerSQLInjections': FxLabs/Common/SQLServer-SQLInjections
  '@MySQLSQLInjections': FxLabs/Common/MySQL-SQLInjections
  
  # No-SQL DB Injection String
  '@MongoDBSQLInjections': FxLabs/Common/MongoDB-SQLInjections
  
  # Cross-Site Scripting Injection Strings
  '@XSSSQLInjections': FxLabs/Common/XSS
  

# App environments
environments:
  - name: Stg
    baseUrl: http://stg1.fxlabs.io/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.io
        password: '{{@Vault.FxLabs/Stg-Admin-Pass}}'
  - name: Local
    baseUrl: http://localhost:8080/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.io
        password: '{{@Vault.FxLabs/DevMachinePassword}}'
  - name: Dev
    baseUrl: http://localhost:8080/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.io
        password: '{{@Vault.FxLabs/DevMachinePassword}}'
# Job profiles
jobs:
  - name: Stg
    environment: Stg
    tags:
      - V1
    regions: FxLabs/US_WEST_1
    cron: '0 30 * ? * *'
    #issueTracker: FxLabs/Stg-GitHub-Bot
  - name: Local
    environment: Local
    tags:
      - V1
    regions: FxLabs/US_WEST_1
    issueTracker: FxLabs/IT-Test
  - name: SANDBOX
    environment: Dev
    tags:
      - SANDBOX
    regions: FxLabs/US_WEST_1
